### ISSUE TITLE
Nothing has been happening recently and I am wondering how stable this is right now.

### ISSUE THREAD

**Issue by JuanPotato** [datamachine/twx.mtproto#1]
So basically a bump

**Comment by xlopo** [comment]
Hello JuanPotato. Life took over for a bit. I have a bunch of code to push this weekend so keep an eye out :) For this exact moment, not stable at all. But again, keep an eye out over the next few days I'll close this ticket when I get something up.

**Comment by JuanPotato** [comment]
Great! Glad to know that you still are here :)
I'll be waiting, may try to help out once you push. I know some python and am really waiting for this project to be finished so that I can finally move away from the bug infested tg-cli ;-;

**Comment by JuanPotato** [comment]
It's been 3 weeks. I just want the latest code with some description so that I can continue this.

**Comment by luckydonald** [comment]
I might join into here aswell, see if I find the time.

**Comment by vanch** [comment]
Also interested from 2016.

**Comment by JuanPotato** [comment]
Dang, 7 months,  this isn't getting up, but I'm slowly making a new library, github.com/libmtproto

**Comment by Surye** [comment]
The botapi has become the priority as I'm more interested in the bot than
the library right now. We have had some discussion how to move this forward
however. And a C++ library is not very relevant to this project.

**Comment by Surye** [comment]
Telegram also has not posted protocol docs in over a year despite they
claiming an open API so I am not happy about that. They have added dozens
of features and many layers that are completely undocumented.

**Comment by luckydonald** [comment]
Fun thing, I just was browsing through this issue earlier today.

**Comment by vanch** [comment]
@JuanPotato there is no useful Python Telegram API lib. C++ is great, but I don't want to write a wrapper for now :)
@Surye wow, you're damn right, I didn't mentioned that last update for API is at 2014.
@luckydonald how's your lib refactoring branch? :) I'm seaching for lib.

**Comment by JuanPotato** [comment]
@vanch there will be bindings ;)

**Comment by luckydonald** [comment]
@vanch  I don't understand..
@JuanPotato Not bad. 
@vanch C# would be worse :D

**Comment by vanch** [comment]
@luckydonald oh, sorry, I made a muddle of https://github.com/griganton/telepy/tree/TL-refactor/
@JuanPotato https://imgflip.com/i/100au2

**Comment by JuanPotato** [comment]
@vanch patience my child

**Comment by JuanPotato** [comment]
@vanch switched to just improving an old go mtproto library, everything is working. Need to make it into an actual library though. https://github.com/JuanPotato/mtproto It works, it exists. It is being worked on. Bindings will come

**Comment by JuanPotato** [comment]
Does that mean this project is back up?

**Comment by Surye** [comment]
It means this isn't an issue, and it's not a forum to discuss other libraries, and so it has no reason to be open. FWIW I am still working on it, but along side other projects as well, no ETAs or roadmaps at this time.
